### ISSUE TITLE
Touch issues (not a report)

### ISSUE THREAD

**Issue by frap129** [Dees-Troy/android_device_google_walleye#1]
I was working on this last night and noticed that google uses modules for some drivers, including the touch driver. Have you made sure that those are included while building and that theyre getting loaded correctly?

**Comment by frap129** [comment]
Modules are located in [https://android.googlesource.com/device/google/wahoo-kernel/+/oreo-dr3-release](url)
EDIT: Running a build with modules included to see if that fixes anything. Added lines 52-56 from [https://android.googlesource.com/device/google/taimen/+/oreo-dr1-dev/BoardConfig.mk](url)

**Comment by DespairFactor** [comment]
Think using my kernel inline will get touch working for you guys, I compiled the modules inline

**Comment by frap129** [comment]
@matthewdalex I already got touch working on mine, however I believe the issue is getting it to work with the stock kernel.

**Comment by DespairFactor** [comment]
@frap129 you have a working build?

**Comment by frap129** [comment]
@matthewdalex touch works, but vibration, decryption, mtp, and adb are broken
